version: '3.8'

services:
  watcher:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: watcher
    restart: always
    ports:
      - "8002:8002"
    privileged: true
    networks:
      - sqli_lab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ../.env.example

networks:
  sqli_lab:
    external: true
